spring.application.name=auth-service
server.port=${SERVER_PORT:8081}
# H2 en archivo — base de datos propia del servicio
spring.datasource.url=jdbc:h2:file:./data/auth_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.settings.web-allow-others=true
spring.datasource.username=dbvalle
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
# Mismo secreto que el monolito original — variable de entorno en Docker
api.security.token.secret=${JWT_SECRET:my-secret-key-that-should-be-very-long}
logging.level.org.springframework.security=DEBUG